# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Plasma Programming Language
email: plasma@plasmalang.org
description: > # this means to ignore newlines until "baseurl:"
  The Plasma programming language strikes a balance between functional and
  imperative programming,
  making it easier to write reliable and efficient software.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://plasmalang.org" # the base hostname & protocol for your site
twitter_username: PlasmaLang
github_path: PaulBone/plasma
contact_page: "http://plasmalang.org/contact.html"

# Build settings
markdown: kramdown

asciidoctor:
    attributes:
          - hardbreaks!

gems:
    - jekyll-asciidoc

